spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
  servlet:
    multipart:
      enabled: true
      max-file-size: 50Mb
      max-request-size: 50Mb
zuul:
  rsa-filter:
    exclude:
    - public
    - mdm

  sensitiveHeaders:
#  sensitive-headers: Cookie,Set-Cookie,Authorization
#  ignore-security-headers: false
#  prefix: /api/v1
  ignoredServices: '*'

  routes:
    public:
      path: /public/**
      serviceId: public-point
      stripPrefix: true

    mdm:
      path: /mdm/**
      serviceId: e-mdm
      stripPrefix: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://10.0.20.116:8801/eureka/,http://10.0.20.116:8802/eureka/

jwt:
  public-key: |
             -----BEGIN PUBLIC KEY-----
             MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs6Ak7AGVxsmjZeRhlTjpThN56QgWNRsCxGtKEw0tj8Bx30xr1a46xpcE91sh41
             Tr9MPXFh/YwUq0wEprv3skCiRAD+Lbo68NReCvhYjbYn6hdiR5QBOlysEF0cO7GTiXgbY2JGkqcj+VlITp8cGiW6PkLIVzEjQXRkFfTToY
             upBKz4Lf7LtAGi+B50mX196yUHTirm6PKKJLcIuooqOHp39ecvaqHwWMloVH0sjTpZh7hvCRpARdxUQ/8KAB8tiFoMsCJPEr/Alr6P64B0
             6oX0VzT68u5lyNQL6h5YaGxUuRwhFuKcvEt3wavHNoHn2FmyJjrhlcRLjyi3jiz/0WjQIDAQAB
             -----END PUBLIC KEY-----