spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168

zuul:
  rsa-filter:
    exclude:
    - e-auth-tokens

  sensitiveHeaders:
#  sensitive-headers: Cookie,Set-Cookie,Authorization
#  ignore-security-headers: false
  prefix: /api/v1
  ignoredServices: '*'

  routes:
    e-auth-tokens:
      path: /auth/tokens
      serviceId: e-auth
      stripPrefix: false
    e-auth-refresh:
      path: /auth/refresh
      serviceId: e-auth
      stripPrefix: false

    e-operation:
      path: /operation/**
      serviceId: e-operation
      stripPrefix: false


#    hello:
#      path: /hello/**
#      serviceId: HelloService
#      url: http://example.com/hello
#      stripPrefix: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://eureka-peer-1:8800/eureka/,http://eureka-peer-2:8800/eureka/

jwt:
  public-key: |
             -----BEGIN PUBLIC KEY-----
             MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs6Ak7AGVxsmjZeRhlTjpThN56QgWNRsCxGtKEw0tj8Bx30xr1a46xpcE91sh41
             Tr9MPXFh/YwUq0wEprv3skCiRAD+Lbo68NReCvhYjbYn6hdiR5QBOlysEF0cO7GTiXgbY2JGkqcj+VlITp8cGiW6PkLIVzEjQXRkFfTToY
             upBKz4Lf7LtAGi+B50mX196yUHTirm6PKKJLcIuooqOHp39ecvaqHwWMloVH0sjTpZh7hvCRpARdxUQ/8KAB8tiFoMsCJPEr/Alr6P64B0
             6oX0VzT68u5lyNQL6h5YaGxUuRwhFuKcvEt3wavHNoHn2FmyJjrhlcRLjyi3jiz/0WjQIDAQAB
             -----END PUBLIC KEY-----


#hello:
#  ribbon:
#    ReadTimeout: 10

#hystrix:
#  command:
#    hello:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5