spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168
  servlet:
    multipart:
      enabled: true
      max-file-size: 50Mb
      max-request-size: 50Mb
zuul:

  sensitiveHeaders:
#  sensitive-headers: Cookie,Set-Cookie,Authorization
#  ignore-security-headers: false
#  prefix: /api/v1
  ignoredServices: '*'

  routes:
    public:
      path: /**
      serviceId: public-point
      stripPrefix: true

    mdm:
      path: /mdm/**
      serviceId: e-mdm
      stripPrefix: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://10.0.20.116:8801/eureka/,http://10.0.20.116:8802/eureka/
